### Registro de usuario y obtener token
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "usuario31@test.com",
  "password": "password123"
}

### Validar email con token
PUT http://localhost:3000/api/auth/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiYzQ4NmFjMzU1MWE5M2E3YjQ5ZSIsImVtYWlsIjoidXN1YXJpbzI3QHRlc3QuY29tIiwiaWF0IjoxNzQzNzY0NTUyLCJleHAiOjE3NDM3NjgxNTJ9.q7IIOVHe8bjyliGVovGEY7I-xGsCX3GktkiZ7DocuPs

{
  "code": "401479"
}

### Login de usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "usuario30@test.com",
  "password": "password123"
}

### Onboarding: Datos personales
PUT http://localhost:3000/api/auth/personal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxOTQzNmE5OGVkM2U1NTI3NDA0MiIsImVtYWlsIjoidXN1YXJpbzE4QHRlc3QuY29tIiwiaWF0IjoxNzQzMDY3NDYwLCJleHAiOjE3NDMwNzEwNjB9.3plvQGa_rwjNYUbht9WPpVrAH2U1_O-Wws495Llb1l8

{
  "nombre": "Sergio",
  "apellidos": "Gómez Perez",
  "nif": "12345678A"
}

### Onboarding: Datos compañía
PATCH http://localhost:3000/api/auth/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTUxOTQzNmE5OGVkM2U1NTI3NDA0MiIsImVtYWlsIjoidXN1YXJpbzE4QHRlc3QuY29tIiwiaWF0IjoxNzQzMDY3NDYwLCJleHAiOjE3NDMwNzEwNjB9.3plvQGa_rwjNYUbht9WPpVrAH2U1_O-Wws495Llb1l8

{
  "nombre": "Empresa SL",
  "cif": "B12345678",
  "direccion": "Calle Mayor 1",
  "esAutonomo": true
}

### Subida de logo (imagen)
PATCH http://localhost:3000/api/auth/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTAxMmE2OTM2YzRkMGVkMzYyZTFhMyIsImVtYWlsIjoidXN1YXJpbzEzQHRlc3QuY29tIiwiaWF0IjoxNzQyNzM4MDg2LCJleHAiOjE3NDI3NDE2ODZ9.8mmRMu3QG51-wbG3y6h2fm-Y7BAVLfungvWQJpVycZI
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="logo"; filename="Logo1.jpg"
Content-Type: image/jpeg

< ./test_assets/Logo1.jpg
--BOUNDARY--

### Obtener mis datos
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZjNjNmFjMzU1MWE5M2E3YjRiZSIsImVtYWlsIjoiaW52aXRhZG8yQHRlc3QuY29tIiwiaWF0IjoxNzQzNzY1NTQ1LCJleHAiOjE3NDM3NjkxNDV9.Tng7DVBhEDpxMSxgye7wtc-QUqua4ekWIw859mcIAos

### Desactivar cuenta (soft delete)
DELETE http://localhost:3000/api/auth/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTAxMmE2OTM2YzRkMGVkMzYyZTFhMyIsImVtYWlsIjoidXN1YXJpbzEzQHRlc3QuY29tIiwiaWF0IjoxNzQyNzQ2MjE3LCJleHAiOjE3NDI3NDk4MTd9.L-egIZQ8ZEqR6ZXvC8Nd-PPvTLveRWXsMVF1hs2xO0M

### Eliminar cuenta (hard delete)
DELETE http://localhost:3000/api/auth/delete?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTAxMmE2OTM2YzRkMGVkMzYyZTFhMyIsImVtYWlsIjoidXN1YXJpbzEzQHRlc3QuY29tIiwiaWF0IjoxNzQyNzQ2MjE3LCJleHAiOjE3NDI3NDk4MTd9.L-egIZQ8ZEqR6ZXvC8Nd-PPvTLveRWXsMVF1hs2xO0M

### Recuperar contraseña - solicitar token
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "usuario10@test.com"
}

### Resetear contraseña con token
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
  "token": "98fc10093d40000115aff79fa1fb88b405bf419224a9290b696f18474bae707a",
  "newPassword": "nuevaPasswordSegura"
}

### Comprobar que se puede hacer login con la nueva contraseña
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "usuario10@test.com",
  "password": "nuevaPasswordSegura"
}

### Invitar compañero con rol guest
POST http://localhost:3000/api/auth/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZjMmVkM2Q4ZTM0ZGVlMGU2ZjE4NSIsImVtYWlsIjoidXN1YXJpbzMxQHRlc3QuY29tIiwiaWF0IjoxNzQzNzY2MjUzLCJleHAiOjE3NDM3Njk4NTN9.brGk0V7VOrAUjwh2tPN0P-oG78AxBSYkI7Pe86ba71Q
Content-Type: application/json

{
  "email": "invitado3@test.com"
}

### Crear cliente
POST http://localhost:3000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQ0MDQ3MDIzLCJleHAiOjE3NDQwNTA2MjN9.tluLew1ll6j_d-gGGzf9nCwNUbmw-ABBRgQADFIaRK4
Content-Type: application/json

{
  "nombre": "Cliente Exclusivo S.L.",
  "email": "cliente@email.com",
  "telefono": "123456789",
  "direccion": "Calle Central 1",
  "ciudad": "Madrid",
  "provincia": "Madrid",
  "codigoPostal": "28001",
  "pais": "España"
}

### Actualizar cliente
PUT http://localhost:3000/api/client/67efbe646ac3551a93a7b4b3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzNzY1MDQ3LCJleHAiOjE3NDM3Njg2NDd9.00OkOzBeggB-OIcz1fW1kwPEUo6w0UA1OGvupO0ApOI
Content-Type: application/json

{
  "nombre": "Cliente Editado S.L.",
  "telefono": "999999999"
}

### Obtener todos los clientes del usuario o compañía
GET http://localhost:3000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzODY2NjU3LCJleHAiOjE3NDM4NzAyNTd9.FpwLqdPyybYNeOPJZJuGlht7lFIAtg1UQWuQz5RBPx8

### Obtener cliente por ID
GET http://localhost:3000/api/client/67efbfbb6ac3551a93a7b4c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzNzY4NzY4LCJleHAiOjE3NDM3NzIzNjh9.dnirCGGTKLxOkWix8bJ98RNh5X96s5AhoAG11-ZaVdE

### Archivar cliente
PATCH http://localhost:3000/api/client/archive/67efbe646ac3551a93a7b4b3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzNzg2NzA1LCJleHAiOjE3NDM3OTAzMDV9.if4PDkkSUL1v8kY1KRDR6HbRvh4Zaf9J_DxxyGL3Ids

### Recuperar cliente
PATCH http://localhost:3000/api/client/recover/67efbe646ac3551a93a7b4b3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzNzg2NzA1LCJleHAiOjE3NDM3OTAzMDV9.if4PDkkSUL1v8kY1KRDR6HbRvh4Zaf9J_DxxyGL3Ids

### Ver clientes archivados
GET http://localhost:3000/api/client/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzNzg2NzA1LCJleHAiOjE3NDM3OTAzMDV9.if4PDkkSUL1v8kY1KRDR6HbRvh4Zaf9J_DxxyGL3Ids

### Eliminar cliente (hard)
DELETE http://localhost:3000/api/client/67efbe646ac3551a93a7b4b3?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzNzg2NzA1LCJleHAiOjE3NDM3OTAzMDV9.if4PDkkSUL1v8kY1KRDR6HbRvh4Zaf9J_DxxyGL3Ids

### Crear un proyecto asociado a un cliente
POST http://localhost:3000/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQ0MDQ3MDIzLCJleHAiOjE3NDQwNTA2MjN9.tluLew1ll6j_d-gGGzf9nCwNUbmw-ABBRgQADFIaRK4
Content-Type: application/json

{
  "nombre": "Proyecto 2025",
  "descripcion": "Albaranes y firma digital",
  "clienteId": "67f40d228fe119dca6e64494"
}

### Editar proyecto existente
PUT http://localhost:3000/api/project/67f11270b4f324009f156fc4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzODUxNDE5LCJleHAiOjE3NDM4NTUwMTl9.5PJ0MIDSxd-2mY090VbmnBe8-HteX7jdm5bQfLb9z-8
Content-Type: application/json

{
  "nombre": "Proyecto Digitalización Actualizado",
  "descripcion": "Actualización de información y requisitos"
}

### Obtener todos los proyectos del usuario
GET http://localhost:3000/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQ0MDQ3MDIzLCJleHAiOjE3NDQwNTA2MjN9.tluLew1ll6j_d-gGGzf9nCwNUbmw-ABBRgQADFIaRK4

### Obtener proyecto específico
GET http://localhost:3000/api/project/67f10fa52ad21027da9f9dd5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzODcyNDM0LCJleHAiOjE3NDM4NzYwMzR9.klBiQnoDofq-5iNCBvx02Oa_I7Em1sYepUIzICcq0mk

### Archivar proyecto
PATCH http://localhost:3000/api/project/archive/67f11270b4f324009f156fc4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzODYxOTc2LCJleHAiOjE3NDM4NjU1NzZ9.OkkqtRdcbtLzpctwHGoTqjfvrMef42TAYnz91AXb8ws

### Recuperar proyecto
PATCH http://localhost:3000/api/project/recover/67f11270b4f324009f156fc4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzODYxOTc2LCJleHAiOjE3NDM4NjU1NzZ9.OkkqtRdcbtLzpctwHGoTqjfvrMef42TAYnz91AXb8ws

### Ver todos los proyectos archivados
GET http://localhost:3000/api/project/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzODYxOTc2LCJleHAiOjE3NDM4NjU1NzZ9.OkkqtRdcbtLzpctwHGoTqjfvrMef42TAYnz91AXb8ws

### Eliminar proyecto permanentemente (hard delete)
DELETE http://localhost:3000/api/project/67f11270b4f324009f156fc4?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQzODYxOTc2LCJleHAiOjE3NDM4NjU1NzZ9.OkkqtRdcbtLzpctwHGoTqjfvrMef42TAYnz91AXb8ws


## ALBARÁN

### Crear albarán con una entrada de horas
POST http://localhost:3000/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQ0MDQ3MDIzLCJleHAiOjE3NDQwNTA2MjN9.tluLew1ll6j_d-gGGzf9nCwNUbmw-ABBRgQADFIaRK4
Content-Type: application/json

{
  "proyecto": "67f10fa52ad21027da9f9dd5",
  "cliente": "67f40d228fe119dca6e64494",
  "items": [
    {
      "tipo": "material",
      "descripcion": "Cables de red CAT6",
      "cantidad": 100,
      "precioUnitario": 0.85
    }
  ]
}

### Obtener todos los albaranes
GET http://localhost:3000/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQ0MDQ3MDIzLCJleHAiOjE3NDQwNTA2MjN9.tluLew1ll6j_d-gGGzf9nCwNUbmw-ABBRgQADFIaRK4

### Ver albarán por ID
GET http://localhost:3000/api/deliverynote/67f40f77d319b50b6835c2ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQ0MDQ3MDIzLCJleHAiOjE3NDQwNTA2MjN9.tluLew1ll6j_d-gGGzf9nCwNUbmw-ABBRgQADFIaRK4

### Descargar PDF del albarán
GET http://localhost:3000/api/deliverynote/pdf/67f4106cd319b50b6835c305
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZiZTBiNmFjMzU1MWE5M2E3YjRhZSIsImVtYWlsIjoidXN1YXJpbzMwQHRlc3QuY29tIiwiaWF0IjoxNzQ0MDQ3MDIzLCJleHAiOjE3NDQwNTA2MjN9.tluLew1ll6j_d-gGGzf9nCwNUbmw-ABBRgQADFIaRK4

